name: hq

channels:
  - astropy

dependencies:
  - python>=3.7
  - astropy
  - numpy
  - scipy
  - matplotlib
  - sqlalchemy
  - pyyaml
  - cython
  - h5py
  - jupyter
  - pandas
  - pip
  - pip:
    - emcee
    - corner
    - tqdm
    - threadpoolctl
    - git+https://github.com/adrn/twobody
    - git+https://github.com/adrn/thejoker
    - git+https://github.com/adrn/schwimmbad
