# flake8: noqa

## This is a template configuration file for running HQ. Most of these settings
## are parameters that relate to The Joker: http://thejoker.readthedocs.io/
## When settings are required, they are noted, and will error if left
## unmodified. Other parameters have defaults set in the file below.

##############################################################################
## General parameters and data loading:
##

## The name of the run (string):
name: 'hqtest'

## A brief description of the run:
description: ''

## A path to a directory where HQ will store data products:
## (this defaults to the path where this config file sits)
cache_path: null

## The path to the source data file, which should contain radial velocity
## measurements, one per row, for multiple sources, and the data format as a
## string, which is passed to Astropy's Table reader:
# TODO: need to edit this file from a test setup() !!
input_data_file: '~/projects/hq/hq/tests/test-allVisit.fits'
input_data_format: null  # (e.g., 'fits' or 'ascii.csv')

## The column name in the input data file that is unique per source:
source_id_colname: 'APOGEE_ID'

## The column names in the input data file that contains the radial velocity,
## time, and radial velocity uncertainty data:
rv_colname: 'VHELIO'
rv_error_colname: 'VRELERR'
time_colname: 'JD'
time_format: 'jd'
time_scale: 'tdb'


##############################################################################
## Prior and sampling parameters for The Joker:
##

## Name of the prior definition file:
prior_file: 'prior.py'

## Number of prior samples to generate and cache:
n_prior_samples: 1_000_000

## The maximum number of prior samples to use when running The Joker:
## (this defaults to the value set in n_prior_samples)
max_prior_samples: null

## Name of the prior cache file to generate and/or use:
## (this defaults to a filename in the cache_path)
prior_cache_file: null

## The number of posterior samples to generate per source:
requested_samples_per_star: 32

## Randomly draw samples from the prior cache:
randomize_prior_order: True


##############################################################################
## Sampling parameters for MCMC:
##

## These parameters are passed directly to pymc3.sample()
tune: 100
draws: 100

## This is the target acceptance ratio used for computing the dense mass matrix:
target_accept: 0.95
