# flake8: noqa

## This is a template configuration file for running HQ. Most of these settings
## are parameters that relate to The Joker: http://thejoker.readthedocs.io/
## When settings are required, they are noted, and will error if left
## unmodified. Other parameters have defaults set in the file below.

##############################################################################
## General parameters and data loading:
##

## The name of the run (string):
name: null  # REQUIRED

## A brief description of the run:
description: ''

## A path to a directory where HQ will store data products:
## (this defaults to the path where this config file sits)
cache_path: null

## The path to the source data file, which should contain radial velocity
## measurements, one per row, for multiple sources, and the data format as a
## string, which is passed to Astropy's Table reader:
input_data_file: null  # REQUIRED
input_data_format: null  # (e.g., 'fits' or 'ascii.csv')

## The column name in the input data file that is unique per source:
source_id_colname: null  # REQUIRED

## The column names in the input data file that contains the radial velocity,
## time, and radial velocity uncertainty data:
rv_colname: null  # REQUIRED
rv_error_colname: null  # REQUIRED
rv_unit: 'km/s'  # any unit string that can be parsed by astropy.units
time_colname: null  # REQUIRED
time_format: null  # REQUIRED (e.g., 'jd' or 'mjd')
time_scale: 'utc'  # (e.g., 'utc' or 'tdb' for Solar System barycentric)


##############################################################################
## Prior and sampling parameters for The Joker:
##

## Name of the prior definition file:
prior_file: 'prior.py'

## Number of prior samples to generate and cache:
n_prior_samples: 500_000_000

## The maximum number of prior samples to use when running The Joker:
## (this defaults to the value set in n_prior_samples)
max_prior_samples: null

## Name of the prior cache file to generate and/or use:
## (this defaults to a filename in the cache_path)
prior_cache_file: null

## The number of posterior samples to generate per source:
requested_samples_per_star: 1024

## Randomly draw samples from the prior cache:
randomize_prior_order: True

## Size of the initial batch of prior samples to use in iterative rejection
## sampling. This must be smaller than the total number of prior samples.
## (defaults to min(250_000, n_prior_samples))
init_batch_size: null

## Parameters for re-running The Joker after the initial run, for stubborn data
## The largest peak-to-peak (max(log10(P)) - max(log10(P))) spread in period
## samples to allow in the rerun sample:
rerun_logP_ptp_threshold: 1.

## The factor to use in setting the rerun period range for unimodal samplings:
rerun_P_factor: 2.5

## The number of prior samples to generate in each rerun:
rerun_n_prior_samples: 10_000_000

##############################################################################
## Sampling parameters for MCMC:
##

## These parameters are passed directly to pymc.sample()
mcmc_tune_steps: 1000
mcmc_draw_steps: 1000
mcmc_chains: 4

## Maximum threshold value of the Gelman-Rubin convergence statistic to consider
## a sampling "successful"
mcmc_max_r_hat: 1.2

## This is the target acceptance ratio used for computing the dense mass matrix:
mcmc_target_accept: 0.95
